name: Branch Check

on:
  push:
  pull_request:

jobs:
  check-diff:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.diff-check.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Branch Difference
        id: diff-check
        shell: bash
        run: |
          git fetch origin experimental
          if git diff --quiet HEAD FETCH_HEAD~1; then
            echo "HEAD matches experimental~1. Skipping main workflow."
            echo "should_run=false" >> $GITHUB_OUTPUT
          else
            echo "HEAD differs from experimental~1. Proceeding to main workflow."
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi